services:
  # Mailhog for testing...
  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025
  # Redis isn't as customized, use off the shelf
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - ./shared/redis:/data
    shm_size: '512m'

  # separate db instance
  # migrate to separated postgres data
  #https://github.com/docker-library/postgres/pull/1259
  # built from https://github.com/discourse/postgresql
  db:
    image: discourse/postgres
    restart: unless-stopped
    volumes:
      - ./shared/db:/var/lib/postgresql
      - ./shared/db/data:/var/lib/postgresql/data
    environment:
      DB_PASSWORD: SOME_SECRET
    shm_size: '512m'

  # zero config/plugin batteries included image built from https://github.com/featheredtoast/discourse-docker-compose/blob/main/.github/workflows/push-web-only.yml
  # built from `launcher build web_only`
  web:
    image: discourse/discourse
    restart: unless-stopped
    volumes:
      - ./shared/web:/shared
    environment:
      DISCOURSE_DB_HOST: db
      DISCOURSE_DB_PASSWORD: SOME_SECRET
      DISCOURSE_DEVELOPER_EMAILS: user@example.com
      DISCOURSE_HOSTNAME: localhost
      DISCOURSE_REDIS_HOST: redis
      DISCOURSE_SMTP_ADDRESS: mail
      DISCOURSE_SMTP_PORT: 1025
      DISCOURSE_SMTP_PASSWORD: pa$$word
      DISCOURSE_SMTP_USER_NAME: user@example.com
      # Uncomment and configure to set up let's encrypt for ssl termination
      # LETSENCRYPT_ACCOUNT_EMAIL: test@example.com
    ports:
      - 443:443
      - 80:80
    depends_on:
      - db
      - redis
    shm_size: '512m'
