services:
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - ./shared/redis:/data
    shm_size: '512m'

  db:
    image: discourse/postgres
    restart: unless-stopped
    volumes:
      - ./shared/db:/var/lib/postgresql
      - ./shared/db/data:/var/lib/postgresql/data
    environment:
      DB_PASSWORD: SOME_SECRET
    shm_size: '512m'

  web:
    image: discourse/discourse
    restart: unless-stopped
    volumes:
      - ./shared/web:/shared
    environment:
      # Connect with the databases above
      DISCOURSE_DB_HOST: db
      DISCOURSE_DB_PASSWORD: SOME_SECRET
      DISCOURSE_REDIS_HOST: redis

      # Edit DISCOURSE_ values with your own config
      DISCOURSE_DEVELOPER_EMAILS: user@example.com
      DISCOURSE_HOSTNAME: site.example.com
      DISCOURSE_SMTP_ADDRESS: mail.example.com
      DISCOURSE_SMTP_PORT: 1025
      DISCOURSE_SMTP_PASSWORD: pa$$word
      DISCOURSE_SMTP_USER_NAME: user@example.com
      # Uncomment and configure to set up let's encrypt for https
      # LETSENCRYPT_ACCOUNT_EMAIL: test@example.com
      # Optional: list any desired extra domains to let's encrypt requests
      # DISCOURSE_HOSTNAME_ALIASES: site2.example.com,site3.example.com
    ports:
      - 443:443
      - 80:80
    depends_on:
      - db
      - redis
    shm_size: '512m'
